add/edit files for MEIC

diff --git a/PREPINPUT/precheck b/PREPINPUT/precheck
--- a/PREPINPUT/precheck
+++ b/PREPINPUT/precheck
@@ -34,17 +34,17 @@ fi
 # Reset the namelist to default state
 python "$pyprog" tempmod
 
-# Verify that the settings needed for NEI and MEGAN are present in the current namelist
+# Verify that the settings needed for MEIC and MEGAN are present in the current namelist
 badopts=false
 
 if ! $metonly; then
-    # Check various options needed for NEI to work
-    python $pyprog check-wrf-opt --io_form_auxinput5=2,11 --io_style_emissions=1 --emiss_inpt_opt=1
+    # Check various options needed for MEIC to work
+    python $pyprog check-wrf-opt --io_form_auxinput5=2,11 --io_style_emissions=1 --emiss_inpt_opt=111
     optchk=$?
     if [ $optchk -gt 0 ]; then
         echo ""
-        echo "One or more of the namelist options expected if using NEI are incorrect."
-        echo "Run 'autowrfchem config namelist' and use the NEI compatibility checker"
+        echo "One or more of the namelist options expected if using MEIC are incorrect."
+        echo "Run 'autowrfchem config namelist' and use the MEIC compatibility checker"
         echo "on the current namelist."
         badopts=true
     fi
@@ -75,7 +75,7 @@ if ! $metonly; then
 fi
 
 # Make sure that the met directory exists as does the mozbc file and the 
-# MEGAN and NEI data
+# MEGAN and MEIC data
 if [ -f "$mydir/../wrfbuild.cfg" ]; then
     . "$mydir/../wrfbuild.cfg" # source the file with metType, metDir, and mozbcFile in it
 else
@@ -107,6 +107,8 @@ if ! $chemonly; then
         # Check if the met directory has untarred GRIB files or tar archives
         if [[ $metType == 'NARR' ]]; then
             grib_prefix='merged_AWIP32'
+        elif [[ $metType == 'ERA5' ]]; then
+            grib_prefix='ecmf_'
         else
             echo "Met type '$metType' not recognized"
         fi
@@ -142,7 +144,7 @@ if ! $chemonly; then
     # Need to go back to WPS directory so the relative paths work
     cd "$wpsdir"
 
-    # Also check the geog_data_path and constants file
+    # Also check the geog_data_path
     geogpath="`python $pyprog get-wps-opt --no-quotes --geog_data_path`"
     if [ $? -ne 0 ]; then
         echo ""
@@ -155,38 +157,21 @@ if ! $chemonly; then
     else:
         echo "Pass: WPS geog_data_path is a directory"
     fi
-    constfile="`python $pyprog get-wps-opt --no-quotes --constants_name`"
-    if [ $? -ne 0 ]; then
-        echo ""
-        echo "Fail: The option 'constants_name' is not specified in the WPS namelist, and it should be."
-        badopts=true
-    elif [ ! -f "$constfile" ]; then
-        echo ""
-        echo "Fail: The WPS constants file $constfile does not exist."
-        badopts=true
-    else
-        echo "Pass: WPS constants file found."
-    fi
+    #constfile="`python $pyprog get-wps-opt --no-quotes --constants_name`"
+    #if [ $? -ne 0 ]; then
+    #    echo ""
+    #    echo "Fail: The option 'constants_name' is not specified in the WPS namelist, and it should be."
+    #    badopts=true
+    #elif [ ! -f "$constfile" ]; then
+    #    echo ""
+    #    echo "Fail: The WPS constants file $constfile does not exist."
+    #    badopts=true
+    #else
+    #    echo "Pass: WPS constants file found."
+    #fi
 fi
 
 if ! $metonly; then
-    cd "$rootdir/NEI"
-    ls 2011/area4k >& /dev/null
-    areatst=$?
-    ls 2011/point >& /dev/null
-    pointtst=$?
-    if [ $areatst -ne 0 -o $pointtst -ne 0 ]; then
-        echo ""
-        echo "Fail: Could not find 2011/area4k and/or 2011/point in NEI."
-        echo "Is the directory 2011 present or linked there?"
-        echo "Does it contain area4k and point as immediate subdirectories?"
-        badopts=true
-    else
-        echo ""
-        echo "Pass: Found NEI/2011/area4k and NEI/2011/point"
-    fi
-    # Check 2005 under certain conditions?
-
     cd "$rootdir/MEGAN"
     ls data/lai* >& /dev/null
     megtst=$?
